### ISSUE TITLE
Apply font smoothing

### ISSUE THREAD

**Issue by adrenth** [adrenth/oc-coffeemanager-plugin#28]
```css
* {  
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility; 
} 
```
